name: test
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.x.x
      - run: opam install -y ppx_deriving 
      - run: opam install -y batteries 
      - run: opam install -y ppx_deriving_yojson 
      - run: opam install -y menhir 
      - run: opam install -y core
      - run: opam install -y fmt
      - run: eval $(opam env)
      - run: dune exec khasmc test/stdlib.kha test/fib.kha
      - run: sudo apt install -y lua5.4
      - run: echo "Lua:" && lua out.lua
