name: test
run-name: ${{ github.actor }} is testing
on:
  push:
    branches:
      - main
jobs:
  check-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.x.x
      - run: opam install . --deps-only
      - run: opam install menhir ppx_deriving_yojson core batteries
      - run: opam exec -- dune build
      - run: opam exec -- dune exec khasmc test/stdlib.kha test/fib.kha
